# -*- coding: utf-8 -*-
"""Waste-Classification-System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLwhp6ISJteEZ06UPEMMuhpZ3jevd-Pl
"""

import tensorflow as tf
tf.config.list_physical_devices('GPU')

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import uuid

dataset_path = "/content/drive/MyDrive/dataset"

for category in os.listdir(dataset_path):
    category_path = os.path.join(dataset_path, category)

    for subfolder in os.listdir(category_path):
        sub_path = os.path.join(category_path, subfolder)

        if os.path.isdir(sub_path):

            for file in os.listdir(sub_path):

                src = os.path.join(sub_path, file)

                # create unique filename
                new_name = str(uuid.uuid4()) + ".jpg"
                dst = os.path.join(category_path, new_name)

                shutil.move(src, dst)

            os.rmdir(sub_path)

print("Dataset structure fixed successfully!")

import os

for folder in os.listdir("/content/drive/MyDrive/dataset"):
    print(folder, "->", len(os.listdir(f"/content/drive/MyDrive/dataset/{folder}")))

# 1. BETTER DATA SPLITTING - Split by samples, not batches
import os
import cv2
import numpy as np
from PIL import Image
import tensorflow as tf
from sklearn.model_selection import train_test_split

# First, thoroughly clean the dataset
import os
import cv2
import numpy as np
from PIL import Image
import imghdr
import traceback
import warnings
warnings.filterwarnings('ignore')  # Temporarily ignore warnings during cleaning

def aggressive_dataset_cleaner(dataset_path):
    """
    Aggressively clean dataset by testing multiple loading methods
    and removing any file that causes warnings or errors
    """
    removed_count = 0
    warning_count = 0

    # Valid image extensions
    valid_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff', '.webp')

    print("Starting aggressive dataset cleaning...")
    print("-" * 50)

    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            file_path = os.path.join(root, file)
            file_size = os.path.getsize(file_path)

            # Remove empty files
            if file_size == 0:
                print(f"Removing empty file: {file}")
                os.remove(file_path)
                removed_count += 1
                continue

            # Check extension
            if not file.lower().endswith(valid_extensions):
                print(f"Removing file with invalid extension: {file}")
                os.remove(file_path)
                removed_count += 1
                continue

            # Test 1: Try with imghdr
            try:
                image_type = imghdr.what(file_path)
                if image_type not in ['jpeg', 'png', 'gif', 'bmp', 'tiff']:
                    print(f"Removing file with invalid image type ({image_type}): {file}")
                    os.remove(file_path)
                    removed_count += 1
                    continue
            except:
                pass

            # Test 2: Try with PIL
            try:
                # Try to open and verify
                with Image.open(file_path) as img:
                    img.verify()

                # Try to actually load and convert
                with Image.open(file_path) as img:
                    # Try to convert to RGB
                    img = img.convert('RGB')

                    # Check dimensions
                    if img.size[0] < 50 or img.size[1] < 50:
                        print(f"Removing too small image ({img.size}): {file}")
                        os.remove(file_path)
                        removed_count += 1
                        continue

                    # Try to get pixel data
                    np.array(img)

            except Exception as e:
                print(f"Removing PIL-corrupted file: {file} - Error: {str(e)[:50]}")
                os.remove(file_path)
                removed_count += 1
                continue

            # Test 3: Try with OpenCV
            try:
                img = cv2.imread(file_path)
                if img is None:
                    print(f"Removing OpenCV-corrupted file: {file}")
                    os.remove(file_path)
                    removed_count += 1
                    continue

                # Check dimensions
                if img.shape[0] < 50 or img.shape[1] < 50:
                    print(f"Removing too small image (OpenCV): {file}")
                    os.remove(file_path)
                    removed_count += 1
                    continue

            except Exception as e:
                print(f"Removing OpenCV-error file: {file} - Error: {str(e)[:50]}")
                os.remove(file_path)
                removed_count += 1
                continue

            # Test 4: Try with TensorFlow
            try:
                image_data = tf.io.read_file(file_path)
                tf.image.decode_image(image_data, channels=3)
            except Exception as e:
                print(f"Removing TensorFlow-corrupted file: {file} - Error: {str(e)[:50]}")
                os.remove(file_path)
                removed_count += 1
                continue

            # If we got here, the file is good
            if removed_count % 10 == 0 and removed_count > 0:
                print(f"Progress: {removed_count} files removed so far...")

    print("-" * 50)
    print(f"Cleaning complete! Removed {removed_count} problematic files.")
    return removed_count

# Run the aggressive cleaner
dataset_path = "/content/drive/MyDrive/dataset"
removed = aggressive_dataset_cleaner(dataset_path)
print(f"Total files removed: {removed}")

# Now verify what's left
print("\n" + "="*50)
print("Dataset summary after cleaning:")
print("="*50)

for class_name in sorted(os.listdir(dataset_path)):
    class_path = os.path.join(dataset_path, class_name)
    if os.path.isdir(class_path):
        image_count = len([f for f in os.listdir(class_path)
                          if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.gif'))])
        print(f"{class_name}: {image_count} images")

import tensorflow as tf
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# Configuration
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
dataset_path = "/content/drive/MyDrive/dataset"

# 1. Get class names and counts
class_names = sorted(['Biodegradable', 'Hazardous', 'Recyclable'])
print("Classes:", class_names)
print(f"Biodegradable: 647 images")
print(f"Hazardous: 1537 images")
print(f"Recyclable: 630 images")

# 2. Collect file paths
file_paths = []
labels = []

for idx,cls in enumerate(class_names):
    path = os.path.join(dataset_path,cls)
    for img in os.listdir(path):
        file_paths.append(os.path.join(path,img))
        labels.append(idx)

# 3. Stratified split (maintains class distribution)
X_train,X_temp,y_train,y_temp = train_test_split(
    file_paths,labels,
    test_size=0.3,
    stratify=labels,
    random_state=42)

X_val,X_test,y_val,y_test = train_test_split(
    X_temp,y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42)

# class weights
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(labels),
    y=labels)

class_weight_dict = {i:class_weights[i] for i in range(3)}

# dataset loader
def load_image(path,label):

    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img,channels=3)
    img = tf.image.resize(img,IMG_SIZE)
    img = preprocess_input(img)

    return img,label

# augmentation
def augment(img,label):

    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_flip_up_down(img)
    img = tf.image.random_brightness(img,0.2)
    img = tf.image.random_contrast(img,0.8,1.2)

    return img,label

AUTOTUNE = tf.data.AUTOTUNE

train_ds = tf.data.Dataset.from_tensor_slices((X_train,y_train))
train_ds = train_ds.map(load_image,num_parallel_calls=AUTOTUNE)
train_ds = train_ds.map(augment,num_parallel_calls=AUTOTUNE)
train_ds = train_ds.shuffle(2000).batch(BATCH_SIZE).prefetch(AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices((X_val,y_val))
val_ds = val_ds.map(load_image,num_parallel_calls=AUTOTUNE)
val_ds = val_ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)

test_ds = tf.data.Dataset.from_tensor_slices((X_test,y_test))
test_ds = test_ds.map(load_image,num_parallel_calls=AUTOTUNE)
test_ds = test_ds.batch(BATCH_SIZE)

# MODEL
base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3))

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(256,activation='relu')(x)
x = Dropout(0.5)(x)

outputs = Dense(3,activation='softmax')(x)

model = Model(base_model.input,outputs)

model.compile(
    optimizer=Adam(learning_rate=3e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

callbacks = [
EarlyStopping(patience=8,restore_best_weights=True),
ReduceLROnPlateau(patience=4,factor=0.3),
ModelCheckpoint("best_model.h5",save_best_only=True)
]

print("Stage 1 Training")

history1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    class_weight=class_weight_dict,
    callbacks=callbacks)

# Fine tuning
base_model.trainable = True

for layer in base_model.layers[:-40]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-6),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Stage 2 Fine Tuning")

history2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    class_weight=class_weight_dict,
    callbacks=callbacks)

model.load_weights("best_model.h5")

test_loss, test_acc = model.evaluate(test_ds)

print(f"\nTest Accuracy: {test_acc:.4f}")

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

y_true = []
y_pred = []

for images, labels in test_ds:

    preds = model.predict(images, verbose=0)

    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print("\nClassification Report:\n")

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names
))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title("Confusion Matrix")
plt.ylabel("True Label")
plt.xlabel("Predicted Label")

plt.show()

import tensorflow as tf

model = tf.keras.models.load_model("/content/drive/MyDrive/waste_classifier (2).keras")

model.save("waste_classifier.keras")

from google.colab import files
files.download("waste_classifier.keras")

model.save("waste_classifier.keras")

import os

output_folder = "/content/drive/MyDrive/waste_project_outputs"

os.makedirs(output_folder, exist_ok=True)

print("Folder created:", output_folder)

import tensorflow as tf

model = tf.keras.models.load_model("/content/drive/MyDrive/waste_classifier.keras")

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open(filename)

plt.imshow(img)
plt.axis("off")
plt.title("Uploaded Image")
plt.show()

import numpy as np
from PIL import Image
import os
from tensorflow.keras.applications.efficientnet import preprocess_input
import shutil
import time

IMG_SIZE = (224,224)

class_names = ["Biodegradable","Hazardous","Recyclable"]

suggestions = {
"Biodegradable":"Dispose in compost bin",
"Recyclable":"Dispose in recycling bin",
"Hazardous":"Dispose in hazardous waste bin"
}

for filename in uploaded.keys():

    img = Image.open(filename).convert("RGB")
    img_resized = img.resize(IMG_SIZE)

    img_array = np.array(img_resized)
    img_array = preprocess_input(img_array)
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)

    predicted_class = class_names[np.argmax(preds)]
    confidence = float(np.max(preds)*100)

    suggestion = suggestions[predicted_class]

    print("Prediction:", predicted_class)
    print("Confidence:", f"{confidence:.2f}%")
    print("Suggestion:", suggestion)

    # save uploaded image to drive
    timestamp = int(time.time())
    save_path = os.path.join(output_folder, f"{timestamp}_{filename}")

    shutil.move(filename, save_path)

    print("Saved to:", save_path)

import shutil

plt.imshow(img)
plt.title(f"{predicted_class} ({confidence:.2f}%)")
plt.axis("off")
plt.show()

print("Suggestion:", suggestions[predicted_class])

img.save(save_path)
print("Saved to:", save_path)

import csv

log_file = "/content/drive/MyDrive/waste_project_outputs/predictions.csv"

with open(log_file, "a", newline="") as f:
    writer = csv.writer(f)
    writer.writerow([filename, predicted_class, confidence])

#plt.imshow(Image.open(filename))
#plt.title(f"{predicted_class} ({confidence:.2f}%)")
#plt.axis("off")
#plt.show()

#print("Suggestion:", suggestions[predicted_class])